language: python
sudo: required
branches:
  only:
   - master
before_install: 
   - sudo pip install -r requirements.txt > ./build.txt
   - sudo pip install flake8 >> ./build.txt
   - sudo pip install coverage
   - sudo pip install pytest
   - sudo pip install flask_httpauth >> ./build.txt
   - sudo apt-get install git
before_script:
  - git config --global user.email "2041829103@qq.com"
  - git config --global user.name "chengxuHawkwood"
script: 
   - flake8 ../Untitled --exit-zero > ./static_analysis.txt
   - (echo "import nltk" ; echo "nltk.download('all')") | python >> ./build.txt
   - sed -i "14ifrom io import open" /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/vaderSentiment/vaderSentiment.py  
   - sed -i "s/textstat.textstat/.textstat/g"  `grep textstat.textstat -rl /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/textstat/__init__.py`
   - sudo sed -i "s/textstat.textstat/.textstat/g"  `grep textstat.textstat -rl /usr/local/lib/python2.7/dist-packages/textstat/__init__.py`
   - python ./app/model/hate_speech/process.py > ./integration_test.txt
   - pytest ./test/TestApp.py > ./unit_test.txt
   - pytest ./test/test_classifier.py >> ./unit_test.txt
   - pytest ./test/test_analyzer.py >> ./unit_test.txt
   - coverage run -a ./test/test_analyzer.py
   - coverage run -a ./test/test_classifier.py
   - coverage run -a ./test/TestApp.py
   - coverage report -m ./test/test_classifier.py ./test/test_analyzer.py ./test/TestApp.py > ./coverage_report.txt
   - git checkout -b test 
   - git add . 
   - git commit -m "new report"
   - git push -u -f "https://${GH_TOKEN}@github.com/chengxuHawkwood/Untitled.git" test:test